version: "3.9"
services:
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - C:\Users\gorya\Desktop\Java\sber\test_task\src\main\resources\prometheus.yml:/etc/prometheus/prometheus.yml